services:

  backend:
    build: .
    container_name: oracle-java-bot-backend

    ports:
      - "8080:8080"

    env_file:
      - .env

    volumes:
      - ./wallet:/opt/oracle/wallet

    restart: unless-stopped