spring.application.name=oracle-java-bot-backend

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@team43_tp?TNS_ADMIN=wallet
spring.datasource.username=CHATBOT_USER
spring.datasource.password=SolSna260593
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

telegram.bot.enabled=true
telegram.bot.token=8671121723:AAFUUjRBa2otHHDB9aaS4A_qqUTlBooYiAg
telegram.bot.name=claygh_bot
telegram.bot.default-priority-id=2
telegram.bot.default-status-id=1
telegram.bot.default-due-days=7